### ISSUE TITLE
答案统计issue

### ISSUE THREAD

**Issue by microlcl** [microlcl/mysurvey#25]
在“我发起的调查”界面，对应刚发布的survey，没有“答案统计”link，看不到实时的答案。 系统中已经有的“答案统计”link，点击后没有任何反应。

**Comment by microlcl** [comment]
目前能进入答案统计界面了。
但是如果此survey包含“开放性”问题，会报500 error

14:42:08.841 [31707722@qtp-12934710-19] INFO  c.e.m.service.paper.PaperService - in paper select paper service
14:42:09.084 [31707722@qtp-12934710-19] ERROR 500.jsp - For input string: "富豪的生活"
java.lang.NumberFormatException: For input string: "富豪的生活"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48) ~[na:1.6.0_43]
	at java.lang.Integer.parseInt(Integer.java:449) ~[na:1.6.0_43]
	at java.lang.Integer.parseInt(Integer.java:499) ~[na:1.6.0_43]
	at com.eastteam.myprogram.service.answer.AnswerService.answerStatisticsBySurvey(AnswerService.java:64) ~[classes/:na]
	at com.eastteam.myprogram.service.answer.AnswerService$$FastClassByCGLIB$$f98d315d.invoke(<generated>) ~[spring-core-3.2.3.RELEASE.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-3.2.3.RELEASE.jar:3.2.3.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:698) ~[spring-aop-3.2.3.RELEASE.jar:3.2.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.3.RELEASE.jar:3.2.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) ~[spring-tx-3.2.3.RELEASE.jar:3.2.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) ~[spring-tx-3.2.3.RELEASE.jar:3.2.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.3.RELEASE.jar:3.2.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.3.RELEASE.jar:3.2.3.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:631) ~[spring-aop-3.2.3.RELEASE.jar:3.2.3.RELEASE]
	at com.eastteam.myprogram.service.answer.AnswerService$$EnhancerByCGLIB$$cc50d737.answerStatisticsBySurvey(<generated>) ~[spring-core-3.2.3.RELEASE.jar:na]
	at com.eastteam.myprogram.web.survey.SurveyController.answerStatistics(SurveyController.java:347) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_43]

**Comment by microlcl** [comment]
如果此问题是开放性问题，应该不作为统计项来处理。

**Comment by microlcl** [comment]
开发性问题的issue，我们放到https://github.com/microlcl/mysurvey/issues/8 里面进行跟踪。
It's closed now.
