### ISSUE TITLE
”调查问卷答案统计“功能实现

### ISSUE THREAD

**Issue by microlcl** [microlcl/mysurvey#8]
由”我的调查-我发起的调查“页面中跳转而来：
如果调查问卷是”已发布“或者”完成“状态，点击进入”调查问卷答案统计“页面
此页面有两个tab(tab页的实现， bootstrap有标准的实现，可以参考：
http://v2.bootcss.com/components.html#navs
)
Tab1. 统计：
选择题列出每个选项的有多少人选，所占百分比，
问答题暂不做统计处理，可以列出所有的答案（如果有更好的办法，欢迎讨论）
Tab2.  
列出所有答题者的link（如果匿名，只姓名用***表示），点击某一个link，跳转到此答题者的答案页面。

**Comment by microlcl** [comment]
此功能没有实现，

**Comment by microlcl** [comment]
我更新了comment 1 里面的功能描述。这是这个应用的一个核心功能，务必最高优先级实现。

**Comment by microlcl** [comment]
目前能进入答案统计界面了。
但是如果此survey包含“开放性”问题，会报500 error

14:42:08.841 [31707722@qtp-12934710-19] INFO c.e.m.service.paper.PaperService - in paper select paper service
14:42:09.084 [31707722@qtp-12934710-19] ERROR 500.jsp - For input string: "富豪的生活"
java.lang.NumberFormatException: For input string: "富豪的生活"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48) ~[na:1.6.0_43]
at java.lang.Integer.parseInt(Integer.java:449) ~[na:1.6.0_43]
at java.lang.Integer.parseInt(Integer.java:499) ~[na:1.6.0_43]
at com.eastteam.myprogram.service.answer.AnswerService.answerStatisticsBySurvey(AnswerService.java:64) ~[classes/:na]
at com.eastteam.myprogram.service.answer.AnswerService$$FastClassByCGLIB$$f98d315d.invoke() ~[spring-core-3.2.3.RELEASE.jar:na]
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-3.2.3.RELEASE.jar:3.2.3.RELEASE]
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:698) ~[spring-aop-3.2.3.RELEASE.jar:3.2.3.RELEASE]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.3.RELEASE.jar:3.2.3.RELEASE]
at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) ~[spring-tx-3.2.3.RELEASE.jar:3.2.3.RELEASE]
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) ~[spring-tx-3.2.3.RELEASE.jar:3.2.3.RELEASE]
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.3.RELEASE.jar:3.2.3.RELEASE]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.3.RELEASE.jar:3.2.3.RELEASE]
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:631) ~[spring-aop-3.2.3.RELEASE.jar:3.2.3.RELEASE]
at com.eastteam.myprogram.service.answer.AnswerService$$EnhancerByCGLIB$$cc50d737.answerStatisticsBySurvey() ~[spring-core-3.2.3.RELEASE.jar:na]
at com.eastteam.myprogram.web.survey.SurveyController.answerStatistics(SurveyController.java:347) ~[classes/:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_43]

**Comment by microlcl** [comment]
如果此问题是开放性问题，应该不作为统计项来处理
