### ISSUE TITLE
"我参与的调查"功能实现

### ISSUE THREAD

**Issue by microlcl** [microlcl/mysurvey#9]
入口菜单：
”我的调查-->我参与的调查“

列出所有我参与的调查问卷，此列表包含字段：
问卷名称，问卷状态， 更新时间，发起人，期限（deadline）
在deadline之前的调查问卷，点击进入后进入可以修改答案。
超过deadline期限的调查问卷，点击进入后可以查看自己的答案，但是不能修改

**Comment by microlcl** [comment]
BinFeng,
除非已经完成了这个task，不要close这个task。
Thanks.

**Comment by zfdforever** [comment]
Hi microlcl,
这个“我的调查”是放在首页的left里面，和“问题管理”、“调查问卷”一起吗？
里面的“我参与的调查”和“我发起的调查”算是二级菜单吗？

**Comment by microlcl** [comment]
都是左侧的菜单,"我的调查是一级菜单"，‘我参与的调查’是二级菜单。
其实菜单放在何处不重要，先实现功能。

**Comment by microlcl** [comment]
hi FeiDi,
我参与的调查中：
调查问卷查看功能不正常，
http://localhost:8080/mysurvey/survey/show/21
修改也不正常。

**Comment by microlcl** [comment]
FeiDi,
我check了一下，发现你fix了一部分，但是还是有些“我参与的调查”里面的查看功能不正常，比如：
http://localhost:8080/mysurvey/survey/accessSurvey/12
后台异常：
11:15:10.056 [31902506@qtp-10056109-16] ERROR 500.jsp - null
java.lang.NullPointerException: null
	at com.eastteam.myprogram.web.survey.SurveyController.accessSurvey(SurveyController.java:283) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_43]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_43]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_43]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_43]
	at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:219) ~[spring-web-3.2.3.RELEASE.jar:3.2.3.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132) ~[spring-web-3.2.3.RELEASE.jar:3.2.3.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) ~[spring-webmvc-3.2.3.RELEASE.jar:3.2.3.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:745) ~[spring-webmvc-3.2.3.RELEASE.jar:3.2.3.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:686) ~[spring-webmvc-3.2.3.RELEASE.jar:3.2.3.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80) ~[spring-webmvc-3.2.3.RELEASE.jar:3.2.3.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925) [spring-webmvc-3.2.3.RELEASE.jar:3.2.3.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856) [spring-webmvc-3.2.3.RELEASE.jar:3.2.3.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:936) [spring-webmvc-3.2.3.RELEASE.jar:3.2.3.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:827) [spring-webmvc-3.2.3.RELEASE.jar:3.2.3.RELEASE]

我怀疑是data issue, please kindly check it.

**Comment by zfdforever** [comment]
这个是由于没有添加权限过滤，所以在未登录情况下或者当前session过期之后，controller里获取不到session里的user字段，会报空指针异常

**Comment by microlcl** [comment]
FeiDi,
不是这个原因。你登录后，进入“我参与的调查”，然后选择第一个“查看”，
http://localhost:8080/mysurvey/survey/accessSurvey/16
后台显示SurveyController.java的283行有问题：
model.addAttribute("expired", survey.getDeadlineTimestamp().before(new Date()));
应该是deadline为空，我怀疑是data issue。
Please kindly check.
